 question  ,  "public  void  run()  {proxy  proxy  =  proxyfactory.generateproxy();source  source;while  (!isstopped)  {try  {source  =  proxy.getpenfingsources();schedulesource(source);}  catch  (exception  e)  {log.error(""unexpected  exception  caught  while  running""'  'e);}}}public  void  stop()  {this.isstopped  =  true;thread.currentthread().interrupt();}"  ,i  am  run  a  thread  whose  main  action  is  to  call  on  a  proxi  use  a  block  function  and  wait  for  it  to  give  it  something  use  the  known  pattern  of  a  volatil  boolean  and  the  interrupt  but  im  not  sure  it  will  work  when  i  tri  to  add  a  catch  block  for  interruptedexcept  i  get  the  error  unreach  catch  block  for  interruptedexcept  this  except  is  never  thrown  from  the  tri  statement  bodi  so  if  im  never  go  to  get  an  interruptedexcept  this  mean  ill  never  get  out  of  the  block  action  thus  will  never  stopim  a  bit  puzzl  ani  idea  ,  instancefieldinvoc  thisrefer  simpleassignmentexpress  true  objectmethodinvoc    objectvari  simplevari  simpleassignmentexpress        objectvari  simplevari  objectmethodinvoc     