 question  ,  "public  class  joinitself  extends  thread  {public  void  run()  {system.out.println(""inside  the  run  method  "");system.out.println(thread.currentthread().isalive());for(int  i=0;i<5;i++)  {try  {system.out.println(""joining  itself  ..."");thread.currentthread().join();}  catch  (interruptedexception  e)  {e.printstacktrace();}}}public  static  void  main(string[]  args)  {joinitself  j  =  new  joinitself();system.out.println(j.isalive());j.start();system.out.println(j.isalive());system.out.println(""thread  started  ..."");}}"  ,i  am  in  doubt  what  happen  when  a  thread  join  itself  ie  thread  call  the  join  method  on  it  own  i  am  not  get  ani  errorsampl  but  whi  should  i  get  ani  error  ,    objectmethodinvoc  simpleassignmentexpress  