 question  ,  "public  class  executorservicetest  extends  mockitotestcase{  private  int  numthreads;private  executorservice  pool;private  volatile  boolean  interruptedbitset;@overridepublic  void  setup()  {numthreads  =  5;pool  =  executors.newfixedthreadpool(numthreads);}class  taskchecksforinterruptedbit  implements  callable<string>  {@overridepublic  string  call()  throws  exception  {interruptedbitset  =  false;while  (!thread.currentthread().isinterrupted())  {}interruptedbitset  =  thread.currentthread().isinterrupted();return  ""blah"";}}public  void  testcancelsetsinterruptedbitincallable()  throws  exception  {interruptedbitset  =  false;final  future<string>  future  =  pool.submit(new  taskchecksforinterruptedbit());final  boolean  wasjustcancelled  =  future.cancel(true);asserttrue(wasjustcancelled);//  give  time  for  the  thread  to  notice  the  interrupted  bit  and  set  the  flagthread.sleep(5000);//  this  succeeds  when  stepping  through  w/  a  debugger'  '  but  fails  when  running//  the  test  straight.  why?asserttrue(interruptedbitset);asserttrue(future.isdone());asserttrue(future.iscancelled());}}"  ,whi  doe  my  unit  test  succeed  in  debug  mode  but  fail  when  run  it  normal  ,    constant  constantinitializationstat  stringdatatyp  simpleassignmentexpress  objectmethodinvoc  actualmethodparamet  objectcreationstat  constructorcal  booleandatatyp  true     