 question  ,  "public  class  threads2  implements  runnable  {public  void  run()  {system.out.println(""run."");throw  new  runtimeexception(""problem"");}public  static  void  main(string[]  args)  {thread  t  =  new  thread(new  threads2());t.start();system.out.println(""end  of  method."");}};  run.//exception;  runexceptionend  of  method;  runend  of  methodexception"  ,i  predict  the  output  asbut  it  is  show  output  as  or  i  wonder  onc  the  except  has  occur  the  program  will  termin  right  ,                