 question  ,  "while(!  isstopped())  {socket  clientsocket  =  null;try  {clientsocket  =  this.serversocket.accept();}  catch  (ioexception  e)  {if  (isstopped())  {system.out.println(""server  stopped."")  ;return;}throw  new  runtimeexception(""error  accepting  client  connection""'  '  e);};  clientsocket  =  this.serversocket.accept();;  private  synchronized  boolean  isstopped()  {return  this.isstopped;};  public  synchronized  void  stop()  {this.isstopped  =  true;try  {this.serversocket.close();}  catch  (ioexception  e)  {throw  new  runtimeexception(""error  closing  server""'  '  e);}};  stop();  isstopped();  onstop()"  ,ive  got  from  someon  this  exampl  with  a  multithread  server  on  android  but  i  have  a  few  difficulti  in  understand  a  part  of  the  code  what  i  dont  understand  is  what  happen  when  i  have  an  except  at  this  line  from  what  i  can  tell  is  that  this  function  get  call  but  how  it  get  to  close  that  socketcaus  if  u  get  except  in  the  attempt  to  accept  a  client  you  should  close  the  socket  return  by  accept  i  assum  that  this  is  done  in  here  but  where  is  calledhow  it  get  to  make  the  connect  between  andand  what  is  with  that  synchron  hope  ive  been  clear  with  my  unclaritiesthank  u  in  advanc  ,  privatemethodspecifi  synchronizedmethodspecifi  booleandatatyp  returnstat  instancefieldinvoc  thisrefer  simpleassignmentexpress  true  trycatchstat  objectmethodinvoc  throwstat  objectcreationstat  constructorcal  actualmethodparamet  stringliter  stringdatatyp  objectvari  simplevari 